name: Build & Push to Docker Hub

on:
  push:
    branches: [ "main", "develop" ]   # main=prod tag, develop=staging tag
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Optional: cache to speed up builds
      - name: Build & Push (Docker Hub)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Tag rules:
          # - develop → :staging and :<short sha>
          # - main    → :latest and :<short sha>
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/applyify:${{ github.ref_name == 'develop' && 'staging' || 'latest' }}
            ${{ secrets.DOCKERHUB_USERNAME }}/applyify:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
